blank_issues_enabled: false # 不允许用户创建空白 Issue
contact_links:
  - name: 遇到问题请先看《使用中常见问题汇总》！谢谢！！！ # 外部网站名称
    url: https://gitee.com/596392912/mica-mqtt/issues/I45GO7 # 跳转的外部网站目标地址
    about: 该文档可以解决你90%的疑惑 # 跳转外部网站的描述说明
